### ISSUE TITLE
安装依赖没有requirements.txt

### ISSUE THREAD

**Issue by vaqua** [pcrbot/mem_birthday#1]
作者大大,仓库里没requirements.txt, 无法执行
pip install -r requirements.txt -i https://repo.huaweicloud.com/repository/pypi/simple

**Comment by azmiao** [comment]
哦，我人傻了，不用安装依赖的，readme是直接复制以前的东西改的233333，忘记删了

**Comment by vaqua** [comment]
原来如此,谢谢啦
