### ISSUE TITLE
感谢作者，有了这个插件，我天天过生日

### ISSUE THREAD

**Issue by 1055169799** [pcrbot/mem_birthday#4]
![QQ截图20220106105541](https://user-images.githubusercontent.com/41286675/148321002-59302639-34a6-4ce8-a19c-1f8f84a2488d.png)

**Comment by azmiao** [comment]
插件内自带测试用指令“手动更新生日”，请去测试看看有什么问题，插件本应在凌晨2点更新信息的，如有问题请去观察那段时间的日志。

**Comment by 1055169799** [comment]
> 插件内自带测试用指令“手动更新生日”，请去测试看看有什么问题，插件本应在凌晨2点更新信息的，如有问题请去观察那段时间的日志。

好的

**Comment by 1055169799** [comment]
> 插件内自带测试用指令“手动更新生日”，请去测试看看有什么问题，插件本应在凌晨2点更新信息的，如有问题请去观察那段时间的日志。

我看了一下被错误@生日的人员，QQ资料卡里的年龄都是1岁，可能是这个造成的

**Comment by azmiao** [comment]
一岁应该也没问题吧，我这个是当天岁数比前一天大一岁才算生日的，如果一岁应该一直保持1

**Comment by azmiao** [comment]
所以建议可以先用"手动更新生日"指令看一下是否有报错
