### ISSUE TITLE
同一账号在不同群只会收到一次生日提醒

### ISSUE THREAD

**Issue by dfmjndm** [pcrbot/mem_birthday#5]
同一账号在不同群只会收到一次生日提醒
能否让所有群里都提醒生日

**Comment by azmiao** [comment]
理论上不会这样的吧，你确实没有提醒的群没有关闭本功能嘛

**Comment by dfmjndm** [comment]
> 理论上不会这样的吧，你确实没有提醒的群没有关闭本功能嘛

均启用，同一个人在两个群里，一个群发了他的生日提醒，另一个群没发，显示的是其他当天生日的人

**Comment by azmiao** [comment]
> > 理论上不会这样的吧，你确实没有提醒的群没有关闭本功能嘛
> 
> 均启用，同一个人在两个群里，一个群发了他的生日提醒，另一个群没发，显示的是其他当天生日的人

那过两天我看看吧，这几天有点忙没空确认和修复，抱歉啦~

**Comment by azmiao** [comment]
经测试，我这里都是正常的，话说如果某个群是机器人新加入的群，或者那个群员是新入群的群员，再入群1-2天内是无法推送生日祝福的
